spring:
  jpa:
    database: POSTGRESQL
    show-sql: true

  datasource:
    platform: postgres
    url: jdbc:postgresql://172.17.0.2:5432/nmbp
    username: postgres
    password: password
    driverClassName: org.postgresql.Driver